#!/usr/bin/env bash

sudo -v

###############################################################################
# Key
###############################################################################

# key-repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

###############################################################################
# Screenshots
###############################################################################
mkdir -p ~/Desktop/Screenshots
defaults write com.apple.screencapture location ~/Desktop/Screenshots
defaults write com.apple.screencapture type -string "png"
defaults write com.apple.screencapture name "ScreenShot"

###############################################################################
# killall's
###############################################################################
killall SystemUIServer
