[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  execute 'source' VimHome() . '/plugins/neocomplete.vim'
'''

[[plugins]]
repo = 'junegunn/vim-emoji'
on_event = 'InsertEnter'
hook_source = '''
  " http://junegunn.kr/2014/06/emoji-completion-in-vim/
  set completefunc=emoji#complete
'''
