[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'powerline/powerline'
rtp = 'powerline/bindings/vim'
hook_add = '''
  " doc - https://powerline.readthedocs.io/en/master/tips-and-tricks.html
  let s:powerline_vim = CacheHome() . '/dein/repos/github.com/powerline/bindings/vim'
  set rtp+=s:powerline_vim
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  " doc - http://ethanschoonover.com/solarized/vim-colors-solarized
  call Msg('Configure vim-colors-solarized')
  syntax enable
  if has('gui_running')
    set background=light
  else
    set background=dark
  endif
  colorscheme solarized
  let g:solarized_termcolors=256
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
  " unite prefix key
  nnoremap [unite] <Nop>
  nmap <Leader>u [unite]

  nnoremap <silent> [unite]f :<C-u>UniteWithBufferDir -buffer-name=files file file/new<CR>
  nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
  nnoremap <silent> [unite]u :<C-u>Unite file_mru buffer<CR>
  nnoremap <silent> [unite]y :<C-u>Unite history/yank<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_if = "isdirectory(bufname('%'))"
hook_add = '''
  " vimfilerをデフォルトに
  let g:vimfiler_as_default_explorer = 1
  " safe-modeをoffで起動
  let g:vimfiler_safe_mode_by_default = 0
  let g:vimfiler_force_overwrite_statusline = 0

  let g:vimfiler_tree_leaf_icon = ' '
 	let g:vimfiler_tree_opened_icon = '▾'
 	let g:vimfiler_tree_closed_icon = '▸'
 	"let g:vimfiler_file_icon = '-'
 	let g:vimfiler_marked_file_icon = '*'
'''