[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'powerline/powerline'
rtp = 'powerline/bindings/vim'
hook_add = '''
  " doc - https://powerline.readthedocs.io/en/master/tips-and-tricks.html
  call Msg('Configure powerline')
  let s:powerline_vim = CacheHome() . '/dein/repos/github.com/powerline/bindings/vim'
  set rtp+=s:powerline_vim
  set laststatus=2 " Always display the statusline in all windows
  set showtabline=2 " Always display the tabline, even if there is only one tab
  set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  " doc - http://ethanschoonover.com/solarized/vim-colors-solarized
  call Msg('Configure vim-colors-solarized')
  syntax enable
  if has('gui_running')
    set background=light
  else
    set background=dark
  endif
  colorscheme solarized
  let g:solarized_termcolors=256
'''
