#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Shortcuts

if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
  ### https://github.com/seebi/dircolors-solarized
  if [[ -f "${XDG_CONFIG_HOME}/dir_colors/dircolors.ansi-dark" ]]; then
    eval $(dircolors "${XDG_CONFIG_HOME}/dir_colors/dircolors.ansi-dark")
  fi
else # BSD `ls`
  colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -lFh ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -laFh ${colorflag}"

# List only directories
alias lsd='ls -lFh ${colorflag} | grep "^d"'

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

# Always enable colored `grep` output
# Note: GREP_OPTIONS is deprecated; please use an alias or script
alias grep="grep --color=auto"

# ghq + peco - http://qiita.com/itkrt2y/items/0671d1f48e66f21241e2
alias ghql='cd $(ghq root)/$(ghq list | peco)'
alias ghqr='gh browse --repo $(ghq list | peco | cut -d "/" -f 2,3)'

alias x64='exec arch -arch x86_64 /bin/bash --login'
alias arm='exec arch -arch arm64e /bin/bash --login'
