#!/usr/bin/env bash

# Make vim the default editor
export EDITOR="vim"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# starship - https://starship.rs/
# Set before direnv
if type starship &> /dev/null 2>&1; then
    eval "$(starship init bash)"
fi

# direnv - https://direnv.net/
if type direnv > /dev/null 2>&1; then
  eval "$(direnv hook bash)"
fi
