#!/usr/bin/env bash

function docker-mc-env {
  local machine=$1
  if which docker-machine &> /dev/null; then
    eval $(docker-machine env $machine);
  fi
}

function docker-mc-env-unset {
  local machine=$1
  if which docker-machine &> /dev/null; then
    eval $(docker-machine env --unset);
  fi
}

function assume-role {
  if which assume-role &> /dev/null; then
    eval $( $(which assume-role) $@);
  fi
}

function assume-role-unset {
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SESSION_TOKEN
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECURITY_TOKEN
}
