#!/usr/bin/env bash

# openssl
if [ -d ${HOMEBREW_PREFIX}/opt/openssl ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/openssl@1.1/bin:$PATH"
  export LDFLAGS="-L${HOMEBREW_PREFIX}/opt/openssl@1.1l/lib $LDFLAGS"
  export CPPFLAGS="-I${HOMEBREW_PREFIX}/opt/openssl@1.1/include $CPPFLAGS"
  export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/opt/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH"
fi

# coreutils
if [ -d ${HOMEBREW_PREFIX}/opt/coreutils ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin:$PATH"
  export MANPATH="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# gnu-tar
if [ -d ${HOMEBREW_PREFIX}/opt/gnu-tar ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/gnu-tar/libexec/gnubin:$PATH"
  export MANPATH="${HOMEBREW_PREFIX}/opt/gnu-tar/libexec/gnuman:$MANPATH"
fi

# findutils
if [ -d ${HOMEBREW_PREFIX}/opt/findutils ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/findutils/libexec/gnubin:$PATH"
  export MANPATH="${HOMEBREW_PREFIX}/opt/findutils/libexec/gnuman:$MANPATH"
fi

# make
if [ -d ${HOMEBREW_PREFIX}/opt/make ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/make/libexec/gnubin:$PATH"
  export MANPATH="${HOMEBREW_PREFIX}/opt/make/libexec/gnuman:$MANPATH"
fi

# unzip
if [ -d ${HOMEBREW_PREFIX}/opt/unzip ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/unzip/bin:$PATH"
fi

# curl
if [ -d ${HOMEBREW_PREFIX}/opt/curl ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/curl/bin:$PATH"
fi

# Ruby
if [ -d ${HOMEBREW_PREFIX}/opt/ruby ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/ruby/bin:$PATH"
  export LDFLAGS="-L${HOMEBREW_PREFIX}/opt/ruby/lib $LDFLAGS"
  export CPPFLAGS="-I${HOMEBREW_PREFIX}/opt/ruby/include $CPPFLAGS"
fi
