# https://starship.rs/config/

add_newline = true

[character]
#symbol = "➜"

[shell]
disabled = false
format = "[$indicator]($style) "
bash_indicator = "bash"
zsh_indicator = "zsh"
style = "bold yellow"
